version: '3.2'

services:
  web:
    image: wugge/gymeesti-occupancy-web:latest
    restart: "unless-stopped"
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gymeesti-occupancy-web.rule=Host(`gymeesti-occupancy.wug.ge`)"
      - "traefik.http.services.gymeesti-occupancy-web.loadbalancer.server.port=3000"
      - "traefik.http.routers.gymeesti-occupancy-web.tls=true"
      - "traefik.http.routers.gymeesti-occupancy-web.entrypoints=websecure"
  api:
    image: wugge/gymeesti-occupancy-api:latest
    container_name: gymeesti-occupancy-api
    restart: "unless-stopped"
    expose:
      - 3000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      GYMEESTI_API_BASE: ${GYMEESTI_API_BASE}
      GYMEESTI_WHITE_LABEL_ID: ${GYMEESTI_WHITE_LABEL_ID}
      GYMEESTI_EMAIL: ${GYMEESTI_EMAIL}
      GYMEESTI_PASSWORD: ${GYMEESTI_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gymeesti-occupancy-api.rule=Host(`gymeesti-occupancy.wug.ge`) && PathPrefix(`/api`)"
      - "traefik.http.services.gymeesti-occupancy-api.loadbalancer.server.port=3000"
      - "traefik.http.routers.gymeesti-occupancy-api.middlewares=gymeesti-occupancy-api"
      - "traefik.http.middlewares.gymeesti-occupancy-api.replacepathregex.regex=^/api/(.*)"
      - "traefik.http.middlewares.gymeesti-occupancy-api.replacepathregex.replacement=/$$1"
      - "traefik.http.routers.gymeesti-occupancy-api.tls=true"
      - "traefik.http.routers.gymeesti-occupancy-api.entrypoints=websecure"
  gymeesti-occupancy-db:
    image: postgres:17
    ports:
      - 51234:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: default
    volumes:
      - gymeesti-occupancy_db_volume:/var/lib/postgresql/data
  redis:
    image: redis:8.2
    


volumes:
  gymeesti-occupancy_db_volume:

networks:
  default:
    external:
      name:
        traefik_default
